# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["zee.khoo@fauna.com"]
description = "A starter kit for using Fauna on Fastly Compute@Edge"
language = "javascript"
manifest_version = 3
name = "Fastly Compute@Edge Starter kit for Fauna"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.fauna]
      url = "https://db.fauna.com"

  [local_server.dictionaries]

    [local_server.dictionaries.fauna_env_variables]
      format = "inline-toml"

      [local_server.dictionaries.fauna_env_variables.contents]
        FAUNA_ACCESS_KEY = "<secret>"

[scripts]
  build = "npm exec webpack && npm exec js-compute-runtime ./bin/index.js ./bin/main.wasm"